routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::resource('books', 'BookController')->middleware(['is_admin']);

Route::resource('authors', 'AuthorController')->middleware(['is_admin']);;

Route::resource('languages', 'LanguageController')->middleware(['is_admin']);;

Route::resource('genres', 'GenreController')->middleware(['is_admin']);;
Route::resource('publishers', 'PublisherController')->middleware(['is_admin']);;
Route::resource('wishes', 'WishController')->middleware(['is_admin']);;
Route::resource('readers', 'ReaderController')->middleware(['is_admin']);;
Route::resource('checkedouts', 'CheckedOutController')->middleware(['is_admin']);;



Route::get('/user', function () {
    return view('user');
});

Route::get('/login', function () {
    return view('login');
});

Route::get('/register', function () {
    return view('register');
});

Auth::routes();


Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');
Route::get('/home', 'HomeController@index');

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('book_search','BookController@search')->name('book_search')->middleware('is_admin');;
Route::get('author_search','AuthorController@search')->name('author_search')->middleware('is_admin');;
Route::get('genre_search','GenreController@search')->name('genre_search')->middleware('is_admin');;
Route::get('language_search','LanguageController@search')->name('language_search')->middleware('is_admin');;
Route::get('publisher_search','PublisherController@search')->name('publisher_search')->middleware('is_admin');;
Route::get('reader_search','ReaderController@search')->name('reader_search')->middleware('is_admin');;

app/Language.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Language extends Model
{
    protected $fillable = ['name'];

    /**
     * Joins the languages table
     * with the books table.
     *
     * 
     */
    public function books()
    {
        return $this->hasMany(Book::class);
    }
}

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Language;
use Illuminate\Support\Facades\DB;

class LanguageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $languages = Language::all();

        return view('languages/index', compact('languages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('languages/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
        ]);
        $language = Language::create($validatedData);

        return redirect('languages')->with('success', 'Sprache wurde erfolgreich hinzugefügt!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $language = Language::findOrFail($id);

        return view('languages/edit', compact('language'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
        ]);
        Language::whereId($id)->update($validatedData);

        return redirect('languages')->with('success', 'Sprache wurde erfolgreich bearbeitet!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $language = Language::findOrFail($id);
        $language->delete();

        return redirect('languages')->with('success', 'Sprache wurde erfolgreich entfernt!');
    }

    /**
     * Searches the resource by the name.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $validatedData = $request->validate([
            'language_search' => 'min:3',
        ]);

        $search = $request->get('language_search');
        $languages = DB::table('languages')
            ->where('name', 'like', '%' . $search . '%')
            ->get();

        return view('languages/index')
            ->with(compact('languages'));
    }
}

resources/views/languages/create.blade.php
@extends('layout')


@section('title')
<title>Neue Sprache hinzufügen</title>
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Neue Sprache hinzufügen
  </div>
  <div class="card-body">
    <form method="post" action="{{ route('languages.store') }}">
      <div class="form-group">
        @csrf
        <label for="name">Name: </label>
        <input type="text" class="form-control" name="name" />
        @error('name')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
      </div>
      <button type="submit" class="btn btn-primary">Hinzufügen</button>
    </form>
  </div>
</div>
@endsection

resources/views/languages/edit.blade.php
@extends('layout')

@section('title')
<title>Sprache bearbeiten</title>
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Sprache bearbeiten
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('languages.update', $language->id) }}">
      <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="name">Titel:</label>
              <input type="text" class="form-control" name="name" value="{{ $language->name }}"/>
          </div>
          <button type="submit" class="btn btn-primary">Änderungen speichern</button>
      </form>
  </div>
</div>
@endsection

resources/views/languages/index.blade.php
@extends('layout')


@section('title')
<title>Alle Sprachen</title>
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
  <div class="alert alert-success">
    {{ session()->get('success') }}
  </div><br />
  @endif
  <div align="left">
    <div class="col-md-4">
      <form action="{{ route('language_search') }}" method="get" role="search">
        {{ csrf_field() }}
        <div class="input-group">
          <input type="text" class="form-control" name="language_search" placeholder="Nach Sprache suchen..." <span class="input-group-btn">
          <button type="submit" class="btn btn-primary">Suchen</button></span>
          @error('language_search')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
      </form>
    </div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <td>Name</td>
        <td>Funktionen</td>
      </tr>
    </thead>
    <tbody>
      @foreach($languages as $language)
      <tr>
        <td>{{$language->name}}</td>
        <td class="d-flex">
          <a href="{{ route('languages.edit', $language->id)}}"><img src="img/tools.png"></img></a>
          <form action="{{ route('languages.destroy', $language->id)}}" method="post">
            @csrf
            @method('DELETE')
            <input type="image" src="img/bin.png" name="submit" class="px-2">
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <div>
    @endsection