routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::resource('books', 'BookController')->middleware(['is_admin']);

Route::resource('authors', 'AuthorController')->middleware(['is_admin']);;

Route::resource('languages', 'LanguageController')->middleware(['is_admin']);;

Route::resource('genres', 'GenreController')->middleware(['is_admin']);;
Route::resource('publishers', 'PublisherController')->middleware(['is_admin']);;
Route::resource('wishes', 'WishController')->middleware(['is_admin']);;
Route::resource('readers', 'ReaderController')->middleware(['is_admin']);;
Route::resource('checkedouts', 'CheckedOutController')->middleware(['is_admin']);;



Route::get('/user', function () {
    return view('user');
});

Route::get('/login', function () {
    return view('login');
});

Route::get('/register', function () {
    return view('register');
});

Auth::routes();


Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');
Route::get('/home', 'HomeController@index');

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('book_search','BookController@search')->name('book_search')->middleware('is_admin');;
Route::get('author_search','AuthorController@search')->name('author_search')->middleware('is_admin');;
Route::get('genre_search','GenreController@search')->name('genre_search')->middleware('is_admin');;
Route::get('language_search','LanguageController@search')->name('language_search')->middleware('is_admin');;
Route::get('publisher_search','PublisherController@search')->name('publisher_search')->middleware('is_admin');;
Route::get('reader_search','ReaderController@search')->name('reader_search')->middleware('is_admin');;

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = ['title', 'year', 'language_id', 'isbn', 'pages'];

    /**
     * Joins the publishers table
     * with the books table.
     *
     * 
     */
    public function publishers()
    {
        return $this->belongsToMany(Publisher::class);
    }

    /**
     * Joins the authors table
     * with the books table.
     *
     * 
     */
    public function authors()
    {
        return $this->belongsToMany(Author::class);
    }

    /**
     * Joins the genres table
     * with the books table.
     *
     * 
     */
    public function genres()
    {
        return $this->belongsToMany(Genre::class);
    }

    /**
     * Joins the languages table
     * with the books table.
     *
     * 
     */
    public function language()
    {
        return $this->belongsTo(Language::class);
    }

    /**
     * Joins the readers table
     * with the books table.
     *
     * 
     */
    public function readers()
    {
        return $this
            ->belongsToMany(Reader::class, 'book_reader')
            ->using(Checkout::class)
            ->withPivot(['id', 'returndate', 'maxreturndate']);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;
use App\Language;
use App\Genre;
use App\Author;
use App\Publisher;
use Illuminate\Support\Facades\DB;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $books = Book::with(['language', 'authors', 'publishers', 'genres'])->get();

        return view('books/index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $languages = Language::all();
        $genres = Genre::all();
        $authors = Author::all();
        $publishers = Publisher::all();

        return view('books/create', compact('languages', 'genres', 'authors', 'publishers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required|max:255',
            'authors' => 'array|min:1',
            'authors.*' => 'exists:authors,id',
            'year' => 'required|numeric|max:2500',
            'publishers' => 'array|min:1',
            'publishers.*' => 'exists:publishers,id',
            'genres' => 'array|min:1',
            'genres.*' => 'exists:genres,id',
            'language_id' => 'required',
            'isbn' => 'required|numeric|max:9999999999999',
            'pages' => 'required|numeric',
        ]);

        $book = Book::create($validatedData);
        $book->authors()->attach(request('authors'));
        $book->genres()->attach(request('genres'));
        $book->publishers()->attach(request('publishers'));


        return redirect('books')->with('success', 'Buch wurde erfolgreich hinzugefügt!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::findOrFail($id);
        $languages = Language::all();
        $genres = Genre::all();
        $authors = Author::all();
        $publishers = Publisher::all();


        return view('books/show', compact('book', 'languages', 'genres', 'authors', 'publishers'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);
        $languages = Language::all();
        $genres = Genre::all();
        $authors = Author::all();
        $publishers = Publisher::all();

        return view('books/edit', compact('book', 'languages', 'genres', 'authors', 'publishers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $book = Book::findorFail($id);
        $validatedData = $request->validate([
            'title' => 'required|max:255',
            'authors' => 'exists:authors,id',
            'year' => 'required|numeric|max:2500',
            'publishers' => 'exists:publishers,id',
            'genres' => 'exists:genres,id',
            'language_id' => 'required',
            'isbn' => 'required|numeric|max:9999999999999',
            'pages' => 'required|numeric',
        ]);
        $validatedData = $request->all();
        $book->fill($validatedData)->save();
        $book->authors()->attach(request('authors'));
        $book->genres()->attach(request('genres'));
        $book->publishers()->attach(request('publishers'));

        return redirect('books')->with('success', 'Buch wurde erfolgreich bearbeitet!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::findOrFail($id);
        $book->delete();

        return redirect('books')->with('success', 'Buch wurde erfolgreich entfernt!');
    }

    /**
     * Searches the resource by the name.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $validatedData = $request->validate([
            'book_search' => 'min:3',
        ]);

        $search = $request->get('book_search');
        $books = Book::with(['language', 'authors', 'publishers', 'genres'])->where('title', 'like', '%' . $search . '%')->get();

        return view('books/index', compact('books'));
    }
}

resources/views/books/create.blade.php
@extends('layout')


@section('title')
<title>Neues Buch hinzufügen</title>
@section('stylesheets')
<script src="http://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />


@endsection
@section('content')

<style>
    .uper {
        margin-top: 40px;
    }
</style>
<div class="card uper">
    <div class="card-header">
        Neues Buch hinzufügen
    </div>
    <div class="card-body">
        <form method="post" action="{{ route('books.store') }}">

            <div class="form-group">
                @csrf
                <label for="title">Titel:</label>
                <input type="text" class="form-control" name="title" value="{{ old('title')}}" />
                @error('title')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="authors">Author(en):</label>
                <select name="authors[]" multiple class="form-control select2-multi <!-- @error('authors') is-invalid @enderror -->">
                    @foreach ($authors as $author)
                    <option value="{{ $author->id }}" {{ in_array($author->id, old('authors') ?? []) ? 'selected' : '' }}>
                        {{ $author->name }}
                    </option>
                    @endforeach
                </select>
                @error('authors')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="year">Jahr:</label>
                <input type="text" class="form-control" name="year" value="{{ old('year')}}" />
                @error('year')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="publishers">Verlag(e):</label>
                <select name="publishers[]" multiple class="form-control select2-multi <!-- @error('publishers') is-invalid @enderror -->">
                    @foreach ($publishers as $publisher)
                    <option value="{{ $publisher->id }}" {{ in_array($publisher->id, old('publishers') ?? []) ? 'selected' : '' }}>
                        {{ $publisher->name }}
                    </option>
                    @endforeach
                </select>
                @error('publishers')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="genres">Genre(s):
                    @foreach($genres as $genre)
                    <input type="checkbox" name="genres[{{$genre->id}}]" @if(array_key_exists($genre->id, old('genres', []))) checked @endif value="{{ $genre->id }}" > {{$genre->name}}
                    @endforeach
                </label>
                @error('genre.'. $genre->id)
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>

            <div class="form-group">
                <label for="language_id">Sprache:</label>
                <select name="language_id" class="form-control @error('language_id') is-invalid @enderror">
                    <option value="{{ old('language_id')}}">-- {{ __('Spache auswählen') }} --</option>
                    @foreach ($languages as $language)
                    @if (old('language_id') == $language->id)
                    <option value="{{ $language->id }}" selected>{{ $language->name }}</option>
                    @else
                    <option value="{{ $language->id }}">{{ $language->name }}</option>
                    @endif
                    @endforeach
                </select>
                @error('language_id')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="isbn">ISBN:</label>
                <input type="text" class="form-control" name="isbn" value="{{ old('isbn')}}" />
                @error('isbn')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="pages">Seitenzahl:</label>
                <input type="text" class="form-control" name="pages" value="{{ old('pages')}}" />
                @error('pages')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary">Hinzufügen</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(".select2-multi").select2();
</script>

@endsection

resources/views/books/edit.blade.php
@extends('layout')

@section('title')
<title>Buch bearbeiten</title>
@section('stylesheets')
<script src="http://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />


@endsection
@section('content')
<style>
    .uper {
        margin-top: 40px;
    }
</style>

<div class="card uper">
    <div class="card-header">
        Buch bearbeiten
    </div>
    <div class="card-body">
        <form method="post" action="{{ route('books.update', $book->id) }}">
            <div class="form-group">
                @csrf
                @method('PATCH')
                <label for="title">Titel:</label>
                <input type="text" class="form-control" name="title" value="{{ $book->title }}" />
                @error('title')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            
            <div class="form-group">
                <label for="authors">Author(en):</label>
                <select name="authors[]" multiple class="form-control select2-multi <!-- @error('authors') is-invalid @enderror -->">
                    @foreach ($authors as $author)
                    <option value="{{ $author->id }}" {{ in_array($author->id, old('authors') ?? []) ? 'selected' : '' }}>
                        {{ $author->name }}
                    </option>
                    @endforeach
                </select>
                @error('authors')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="year">Jahr:</label>
                <input type="text" class="form-control" name="year" value="{{ $book->year }}" />
                @error('year')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="publishers">Verlag(e):</label>
                <select name="publishers[]" multiple class="form-control select2-multi <!-- @error('publishers') is-invalid @enderror -->">
                    @foreach ($publishers as $publisher)
                    <option value="{{ $publisher->id }}" {{ in_array($publisher->id, old('publishers') ?? []) ? 'selected' : '' }}>
                        {{ $publisher->name }}
                    </option>
                    @endforeach
                </select>
                @error('publishers')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="genres">Genre(s):
                    @foreach($genres as $genre)
                    <input type="checkbox" name="genres[{{$genre->id}}]" @if(array_key_exists($genre->id, old('genres', []))) checked @endif value="{{ $genre->id }}" > {{$genre->name}}
                    @endforeach
                </label>
                @error('genre.'. $genre->id)
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>

            <div class="form-group">
                <label for="language_id">Sprache:</label>
                <select name="language_id" class="form-control @error('language_id') is-invalid @enderror">
                    <option value="{{ old('language_id')}}">-- {{ __('Spache auswählen') }} --</option>
                    @foreach ($languages as $language)
                    @if (old('language_id') == $language->id)
                    <option value="{{ $language->id }}" selected>{{ $language->name }}</option>
                    @else
                    <option value="{{ $language->id }}">{{ $language->name }}</option>
                    @endif
                    @endforeach
                </select>
                @error('language_id')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="isbn">ISBN:</label>
                <input type="text" class="form-control" name="isbn" value="{{ $book->isbn }}" />
                @error('isbn')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="pages">Seitenzahl:</label>
                <input type="text" class="form-control" name="pages" value="{{ $book->pages }}" />
                @error('pages')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Hinzufügen</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(".select2-multi").select2();
</script>
@endsection

resources/views/books/index.blade.php
@extends('layout')


@section('title')
<title>Alle Bücher</title>
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
  <div class="alert alert-success">
    {{ session()->get('success') }}
  </div><br />
  @endif
  <div align="left">
    <div class="col-md-4">
      <form action="{{ route('book_search') }}" method="get" role="search">
        {{ csrf_field() }}
        <div class="input-group">
          <input type="text" class="form-control" name="book_search" placeholder="Nach Titel suchen..." <span class="input-group-btn">
          <button type="submit" class="btn btn-primary">Suchen</button></span>
          @error('book_search')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
      </form>
    </div>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>Titel</td>
        <td>Autor</td>
        <td>Jahr</td>
        <td>Genre</td>
        <td>Sprache</td>
        <td>Funktionen</td>
      </tr>
    </thead>
    <tbody>
      @foreach($books as $book)
      <tr>
        <td>{{$book->title}}</td>
        @foreach($book->authors as $author)
        <td>{{$author->name}}</td>
        @endforeach
        <td>{{$book->year}}</td>
        @foreach($book->genres as $genre)
        <td >{{$genre->name}}</td>
        @endforeach
        <td>{{$book->language->name}}</td>

        <td class="d-flex">
          <a href="{{ route('books.edit', $book->id)}}"><img src="img/tools.png"></img></a>
        <a href="{{ route('books.show', $book->id)}}" class="px-2"><img src="img/view.png"></img></a>
          <form action="{{ route('books.destroy', $book->id)}}" method="post">
            @csrf
            @method('DELETE')
            <input type="image" src="img/bin.png" name="submit">
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <div>
    @endsection

resources/views/books/show.blade.php
@extends('layout')


@section('title')
<title>Alle Bücher</title>
@section('content')
<style>
    .uper {
        margin-top: 40px;
    }
</style>
<div class="uper">
    @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div><br />
    @endif
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> {{ $book->title }}</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('books.index') }}"> Zurück</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>ID:</strong>
                {{ $book->id }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $book->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Autor(en):</strong>
                @foreach($book->authors as $author)
                {{$author->name}}
                @endforeach
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jahr:</strong>
                {{ $book->year }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Verlag(e):</strong>
                @foreach($book->publishers as $publisher)
                {{$publisher->name}}
                @endforeach
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Genre(s):</strong>
                @foreach($book->genres as $genre)
                {{$genre->name}}
                @endforeach
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Sprache:</strong>
                {{$book->language->name}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>ISBN:</strong>
                {{ $book->isbn }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Seitenzahl:</strong>
                {{ $book->pages }}
            </div>
        </div>
    </div>
    @endsection