routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::resource('books', 'BookController')->middleware(['is_admin']);

Route::resource('authors', 'AuthorController')->middleware(['is_admin']);;

Route::resource('languages', 'LanguageController')->middleware(['is_admin']);;

Route::resource('genres', 'GenreController')->middleware(['is_admin']);;
Route::resource('publishers', 'PublisherController')->middleware(['is_admin']);;
Route::resource('wishes', 'WishController')->middleware(['is_admin']);;
Route::resource('readers', 'ReaderController')->middleware(['is_admin']);;
Route::resource('checkedouts', 'CheckedOutController')->middleware(['is_admin']);;



Route::get('/user', function () {
    return view('user');
});

Route::get('/login', function () {
    return view('login');
});

Route::get('/register', function () {
    return view('register');
});

Auth::routes();


Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');
Route::get('/home', 'HomeController@index');

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('book_search','BookController@search')->name('book_search')->middleware('is_admin');;
Route::get('author_search','AuthorController@search')->name('author_search')->middleware('is_admin');;
Route::get('genre_search','GenreController@search')->name('genre_search')->middleware('is_admin');;
Route::get('language_search','LanguageController@search')->name('language_search')->middleware('is_admin');;
Route::get('publisher_search','PublisherController@search')->name('publisher_search')->middleware('is_admin');;
Route::get('reader_search','ReaderController@search')->name('reader_search')->middleware('is_admin');;

app/Genre.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    protected $fillable = ['name'];

    /**
     * Joins the books table
     * with the genres table.
     *
     * 
     */
    public function books()
    {
        return $this->belongsToMany(Book::class);
    }
}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Genre;
use Illuminate\Support\Facades\DB;

class GenreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $genres = Genre::all();

        return view('genres/index', compact('genres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('genres/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
        ]);
        $genre = Genre::create($validatedData);

        return redirect('genres')->with('success', 'Genre wurde erfolgreich hinzugefügt!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $genre = Genre::findOrFail($id);

        return view('genres/edit', compact('genre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
        ]);
        Genre::whereId($id)->update($validatedData);

        return redirect('genres')->with('success', 'Genre wurde erfolgreich bearbeitet!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $genre = Genre::findOrFail($id);
        $genre->delete();

        return redirect('genres')->with('success', 'Genre wurde erfolgreich entfernt!');
    }

    /**
     * Searches the resource by the name.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $validatedData = $request->validate([
            'genre_search' => 'min:3',
        ]);

        $search = $request->get('genre_search');
        $genres = DB::table('genres')
            ->where('name', 'like', '%' . $search . '%')
            ->get();

        return view('genres/index')
            ->with(compact('genres'));
    }
}

resources/views/genres/create.blade.php
@extends('layout')


@section('title')
<title>Neue Genre hinzufügen</title>
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Neue Genre hinzufügen
  </div>
  <div class="card-body">
    <form method="post" action="{{ route('genres.store') }}">
      <div class="form-group">
        @csrf
        <label for="name">Name: </label>
        <input type="text" class="form-control" name="name" />
        @error('name')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
      </div>
      <button type="submit" class="btn btn-primary">Hinzufügen</button>
    </form>
  </div>
</div>
@endsection

resources/views/genres/edit.blade.php
@extends('layout')

@section('title')
<title>Genre bearbeiten</title>
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Genre bearbeiten
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('genres.update', $genre->id) }}">
      <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="name">Titel:</label>
              <input type="text" class="form-control" name="name" value="{{ $genre->name }}"/>
          </div>
          <button type="submit" class="btn btn-primary">Änderungen speichern</button>
      </form>
  </div>
</div>
@endsection

resources/views/genres/index.blade.php
@extends('layout')


@section('title')
<title>Alle Genres</title>
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
  <div class="alert alert-success">
    {{ session()->get('success') }}
  </div><br />
  @endif
  <div align="left">
    <div class="col-md-4">
      <form action="{{ route('genre_search') }}" method="get" role="search">
        {{ csrf_field() }}
        <div class="input-group">
          <input type="text" class="form-control" name="genre_search" placeholder="Nach Genre suchen..." <span class="input-group-btn">
          <button type="submit" class="btn btn-primary">Suchen</button></span>
          @error('genre_search')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
      </form>
    </div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <td>Name</td>
        <td>Funktionen</td>
      </tr>
    </thead>
    <tbody>
      @foreach($genres as $genre)
      <tr>
        <td>{{$genre->name}}</td>
        <td class="d-flex">
          <a href="{{ route('genres.edit', $genre->id)}}"><img src="img/tools.png"></img></a>
          <form action="{{ route('genres.destroy', $genre->id)}}" method="post">
            @csrf
            @method('DELETE')
            <input type="image" src="img/bin.png" name="submit" class="px-2">
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <div>
    @endsection